# application version catalog v0.2.0
[versions]
# plugin
agp = "7.4.0"
ksp = "1.8.21-1.0.11"
sqldelight = "1.5.4"
lintTool = "30.2.0"
composeCompiler = "1.4.0"

# langauge and platform
kotlin = "1.8.0"
composeBom = "2023.01.00" # kotlin 1.8.0
activityCompose = "1.5.1"
lifecycle = "2.5.1"
datastore = "1.0.0"
coreKtx = "1.9.0" # looks legacy
junit = "4.13.2"
junitAndroid = "1.1.5"
espresso = "3.5.1"
materialWidget = "1.7.0"

# common
sugar = "0.0.1-rc.9"
devTools = "0.0.1"
theme = "0.1.4-rc.1"
ctc = "0.1.1"

# other third-party
okhttpBom = "4.10.0"
retrofit = "2.9.0"
logcat = "0.1"
composeDestinations = "1.7.32-beta" # require compose 1.3.x
coilCompose = "2.2.2"
koinAndroid = "3.3.2"
mmkv = "1.2.15"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqldelight" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor" }

androidx-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycle-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
material = { module = "com.google.android.material:material", version.ref = "materialWidget" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material = { module = "androidx.compose.material:material" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }

# compose destination
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "composeDestinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinations" }

# common
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
sql = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }

ctc = { module = "com.github.kkoshin:ctc", version.ref = "ctc" }
sugar = { module = "com.github.foodiestudio:sugar", version.ref = "sugar" }
dev-tools = { module = "com.github.foodiestudio:dev-tools", version.ref = "devTools" }
theme = { module = "com.github.foodiestudio:app-theme", version.ref = "theme" }

# for lint (optional)
lint-core = { module = "com.android.tools.lint:lint", version.ref = "lintTool" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lintTool" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lintTool" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lintTool" }

# for test
junit = { module = "junit:junit", version.ref = "junit" }
junit-android = { module = "androidx.test.ext:junit", version.ref = "junitAndroid" }
junit-compose = { module = "androidx.compose.ui:ui-test-junit4" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[bundles]
jetpack = ["androidx-ktx", "lifecycle-ktx", "datastore", "datastore-preferences", "material"]
compose = ["compose-foundation", "compose-ui", "compose-material", "activity-compose", "compose-livedata", "compose-material-icons"]
network = ["retrofit", "retrofit-converter-gson", "okhttp-logging"]
debug = ["compose-ui-tooling", "dev-tools"]
unit-tests = ["junit"]
android-tests = ["junit-android", "junit-compose", "espresso"]
lint = ["lint-core", "lint-api", "lint-checks", "lint-tests"]
